
main: co.crystaldev.bearconomy.framework.BearconomyPlugin
name: ${pluginName}
description: ${pluginDescription}
version: ${pluginVersion}
authors: [ BestBearr ]
api-version: 1.13
depend:
  - AlpineCore
softdepend:
  - Vault
  - PlaceholderAPI