main: co.crystaldev.bearconomy.framework.BearconomyPlugin
name: Bearconomy
description: "${description}"
version: "${version}"
authors: [ BestBearr ]
api-version: 1.13
depend:
  - AlpineCore
softdepend:
  - Vault
  - PlaceholderAPI